apiVersion: v1
kind: Service
metadata:
  name: appname
  labels:
    app: appname
    type: frontend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: appname
    type: frontend
