apiVersion: v1
kind: Service
metadata:
  name: mysql-ha-service
  labels:
    app: mysql-ha
spec:
  ports:
  - port: 3306
    name: mysql-ha
  clusterIP: None
  selector:
    app: mysql-ha
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-ha
spec:
  selector:
    matchLabels:
      app: mysql-ha # has to match .spec.template.metadata.labels
  serviceName: "mysql-ha-service"
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mysql-ha # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image:  mysql
        resources:
          limits:
            cpu: 750m
            memory: 170Mi
          requests:
            cpu: 750m
            memory: 170Mi
        ports:
        - containerPort: 3306
          name: web
        volumeMounts:
        - name: mysql-ha-storage
          mountPath: /var/lib/mysql
      volumeClaimTemplates:
      - metadata:
          name: mysql-ha-storage
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi