apiVersion: v1
kind: Pod
metadata:
  name: tester-nginx-pod
  labels:
    name: tester-nginx-label-name
spec:
  containers: # list/array of containers inside the pod
  - name: tester-nginx-container # name of container inside the pod
    image: gcr.io/google-containers/nginx
    resources:
      requests:
        cpu: "250m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"
    ports:
      - containerPort: 8080
  nodeSelector: # label a node with key=size and value=large for example
    size: large
    disktype: ssd
  tolerations:
  - key: "name"
    operator: "Equal"
    value: "tester-nginx-pod"
    effect: "NoSchedule"

# ----------------------------------------------------------------------------
# To get current object labels
# kubectl get nodes -o jsonpath='{.items[*].metadata.labels}' | jq .
# ----------------------------------------------------------------------------