# This secrets file was created imparitively using this command
#   kubectl create secret generic my-secret --from-literal=key1=supersecret
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: default
type: Opaque
data:
  key1: c3VwZXJzZWNyZXQ=

# NOTE: The data value for key1 was base64 encoded on the fly.
