apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    name: secret-pod-label
spec:
  containers: # list/array of containers inside the pod
  - name: secret-pod-container # name of container inside the pod
    image: gcr.io/google-containers/nginx
    envFrom: # this is a list; we can pass as many vars as needed
      - secretRef:
          name: my-secret
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
