---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  tester-service-account
---
apiVersion: v1
kind: Pod
metadata:
  name: tester-nginx-pod
  labels:
    name: tester-nginx-label-name
spec:
  serviceAccount: tester-service-account
  containers: # list/array of containers inside the pod
  - name: tester-nginx-container # name of container inside the pod
    image: gcr.io/google-containers/nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080

# Pass a pod name to the script to view the token contents: (example)
# ./unpack-token.sh tester-nginx-pod
