apiVersion: batch/v1
kind: CronJob
metadata:
  name: reporting-cron-job
spec:                                                  # spec for cronjob
  schedule: "*/1 * * * *"  # variable; how often to run the job
  jobTemplate:
    spec:                                              # spec for job
      completions: 3  # variable; how many Pods are required for complete status to be successful?
      parallelism: 3  # variable; how many Pods are run at once?
      template:
        metadata:
          name: reporting-tool
        spec:                                          # spec for container
          containers:
            - image: nginx
              name: reporting-tool
              resources: {}
          restartPolicy: Never

# -------------------------------------------------------------------------------------------------
# This is what the above job looks like from a logging perspective:
# -------------------------------------------------------------------------------------------------
# kubectl create -f cronjobs/cronjob.yaml
# cronjob.batch/reporting-cron-job created
#
# kubectl get cronjobs.batch reporting-cron-job
# NAME                 SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
# reporting-cron-job   */1 * * * *   False     0        <none>          45s
#
# kubectl logs jobs/reporting-cron-job-28245268
# Found 3 pods, using pod/reporting-cron-job-28245268-wrm4n
# /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
# /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
# /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
# 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
# 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
# /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
# /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
# /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
# /docker-entrypoint.sh: Configuration complete; ready for start up
# 2023/09/14 18:28:05 [notice] 1#1: using the "epoll" event method
# 2023/09/14 18:28:05 [notice] 1#1: nginx/1.25.2
# 2023/09/14 18:28:05 [notice] 1#1: built by gcc 12.2.0 (Debian 12.2.0-14)
# 2023/09/14 18:28:05 [notice] 1#1: OS: Linux 5.15.49-linuxkit-pr
# 2023/09/14 18:28:05 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
# 2023/09/14 18:28:05 [notice] 1#1: start worker processes
# 2023/09/14 18:28:05 [notice] 1#1: start worker process 29
# 2023/09/14 18:28:05 [notice] 1#1: start worker process 30
# 2023/09/14 18:28:05 [notice] 1#1: start worker process 31
# 2023/09/14 18:28:05 [notice] 1#1: start worker process 32
# 2023/09/14 18:28:05 [notice] 1#1: start worker process 33
# 2023/09/14 18:28:05 [notice] 1#1: start worker process 34
# -------------------------------------------------------------------------------------------------
# NOTE: 3 containers were started and were allowed to work in parallel
# -------------------------------------------------------------------------------------------------