# Impose Quotas at the NAMESPACE level
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-resource-quota
  labels:
    name: namespace-resource-quota
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
