apiVersion: v1
kind: Pod
metadata:
  name: tester-nginx-pod
  labels:
    name: tester-nginx-label-name
spec:
  containers: # list/array of containers inside the pod
  - name: tester-nginx-container # name of container inside the pod
    image: gcr.io/google-containers/nginx
    resources:
      requests:
        cpu: "250m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"
    ports:
      - containerPort: 8080
