apiVersion: v1
kind: Pod
metadata:
  name: mosquito
  labels:
    name: mosquito
spec:
  containers: # list/array of containers inside the pod
  - name: nginx # name of container inside the pod
    image: gcr.io/google-containers/nginx
    resources:
      requests:
        cpu: "250m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"
    ports:
      - containerPort: 8080
  tolerations:
  - key: "name"
    operator: "Equal"
    value: "mosquito"
    effect: "NoSchedule"
