# This is an initContainer:
# REF: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
# It is configured in a pod like any other container, except that it is
# specified inside its own "initContainers" section.
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    resources:
      requests:
        cpu: "250m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', 'git clone <some-repository-that-will-be-used-by-application> ;']

# * Use initContainers when attempting to run any command or task that will only
# be run one time after the pod is created. The initContainer will complete
# its task before the main container is started.
# * If any of the initContainers fail to complete, Kubernetes restarts the Pod
# repeatedly until the Init Container succeeds.
